### ISSUE TITLE
meta question visualisation

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/lomake#186]
meta questions are the common questions about what information was used and would be needed
- [ ] label questions as a. and b.
- [x] remove their icons from the sidebar
- [x] format them different to other questions, and more like the section title
