### ISSUE TITLE
refactor 'admin mode'

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/lomake#243]
- [x] remove 'admin mode' toggle
- [x] always show 'edit users' to admins (ospa) and superadmins (toska)
- [x] in user list, show hijack only to superadmins
- [ ] add filtering to user list
- [ ] move hidden users to 'hidden users accordion'
- [ ] disallow hiding admin users
