### ISSUE TITLE
upon login, if user belongs to OSPA IAM group, grant them admin rights

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/lomake#311]
DUPLICATE

- [ ] request IAM groups from shibboleth
- [ ] check if user has related IAM group (grp-ko-laadunhallinta)
- [ ] set user as admin

bonus
- [ ] if user belongs to grp-toska, treat user as superadmin
- [ ] remove hardcoded superadmin access
