### ISSUE TITLE
Summary page

### ISSUE THREAD

**Issue by Sendouc** [UniversityOfHelsinkiCS/lomake#346]
# Motivation
Currently the fastest way to view all answers to a question is to go to the Overview Page and click the emoji one by one opening the answers in modal. This is obviously very slow and cumbersome. Let's implement a new page meant for this purpose. In this new page it should be easy to read through all answers from every program the viewer has access to per question.

# Tasks

- [x] Create a new page and add it to react-router
- [x] Link to the page from the overview page (button as a link on the top left corner?)
- Is the button shown to everyone? At least if the user only has access to one program summary
- [x] Create the actual page MVP (see below for suggestion on how exactly)
- [x] Cypress tests

# Suggested implementation

Do all data handling on the frontend side. Data queried on the overview page can be reused here. Maybe could use the [Semantic UI Accordion component](https://react.semantic-ui.com/modules/accordion/) here. Question title being the accordion header and answer showing up when the accordion gets opened. Naturally with each answer it is shown which program the answer is from.

Maybe show badge in the accordion header with the amount of question in the accordion.

You should be able to select the year with a dropdown same as overview page.

#Issues 
#352 Page and adding it to router
#354 View of written answers
#363 Clean up the "disabled" and "only one answer" -mode
#355 View of piecharts
#353 Link summary page to overviewpage
#357 Filtering based on program level
#358 Filtering based on faculty
#364 Search by name
#356 Cypress tests

# Related
#318 (closed in favor of this issue)
#344 fuzzy search for answer
#345 filter answers shown by emoji
