### ISSUE TITLE
Lomake-wide reading rights

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/lomake#422]
The subtasks include: 

- [x] https://github.com/UniversityOfHelsinkiCS/lomake/issues/427 New field in the user-model

- [x] https://github.com/UniversityOfHelsinkiCS/lomake/issues/428 Modifying the admin-field in the user-table

- [x] https://github.com/UniversityOfHelsinkiCS/lomake/issues/429 Grant reading-rights upon login 

- [x] https://github.com/UniversityOfHelsinkiCS/lomake/issues/434 Modify the code to show correct stuff

- [x] https://github.com/UniversityOfHelsinkiCS/lomake/issues/433 Tests

And bonus:

- [ ] https://github.com/UniversityOfHelsinkiCS/lomake/issues/430 toggle for the massive user-list
