### ISSUE TITLE
Oodikone abridgement

### ISSUE THREAD

**Issue by sinikala** [UniversityOfHelsinkiCS/lomake#635]
For evaluation, both programme and faculty level form, add a link to a custom oodikone view

Programme:
- [x] Progress table + graph (from studytracks)
- [x] Graduation times table (by grad year)
- [x] Transferred to/from programme table + graph

Faculty:

- [x] Progress table + graph (from faculty view)
- [x] Graduation times table (from faculty view, by grad year)

For both:

- [x] Link takes directly to a certain programme/faculty
- [x] Exclude all transfers etc AND put that info on the page
- [x] Add mentions/links about what else you can check in Oodikone, eg. where to see how others do in the faculty
