### ISSUE TITLE
Evaluation form for faculty

### ISSUE THREAD

**Issue by sinikala** [UniversityOfHelsinkiCS/lomake#646]
- [ ] Color table as usual, faculties insted of programmes
- [ ]  Some kind of see all answers page where all answers of that faculty's programmes are
- [ ] For question spesific summary, show color pie chart of programmes' answers. Three pies, bachelor, master, doctor. With expand, show what color each programme selected
