### ISSUE TITLE
Refactor all data saving and handling AKA Break everything

### ISSUE THREAD

**Issue by sinikala** [UniversityOfHelsinkiCS/lomake#650]
Basically everything needs to be refactored to enable handling data from multiple different forms.

Consider at least:

- Opening a form -> initialising of  temp data?
- Saving data to old answers
- Backupping
- Retrieving right data for right form
- #645 

To do (at least):

- [x] Add column 'form' to deadline table
- [x] Add column 'Form' to answers table and set yearly form  to all current data
- [x] Add column 'Form' to tempAnswers table and set yearly form to all current data
- [x] Add column 'Form' to backupAnswers table and set yearly form to all current data

- [x] Fix retrieving data from correct form
- [x] Fix saving data to correct form, on join and save 
- [x] Add 'form' prop to all savable elements
- [x] Adjust all components that check deadlines
- [x] Adjust websocketHandlers
- [x] Adjust deadline watcher
- [x] Fix PDF-printing

- [x] Add statusmessage (saved etc to new forms)

- [x] Make form dynamic in tests

Will not do after all?
Create db table 'Forms' with one row for each form type (string: name)
Add forms to seeding ?
